language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.1"
  - "7.2"

before_script:
  - composer install
  - mkdir -p build/logs

script:
  - cd $TRAVIS_BUILD_DIR;
  - vendor/bin/phpunit --configuration tests/phpunit.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - pwd
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
  - php vendor/bin/coveralls -v
